Repository wecode-bootcamp-korea/37-2nd-O2bnb-backend, pull requests merged in 2022-10, with the labels that each got.

#1 [정다영- O2bnb] Second Project 초기셋팅
  .gitignore
  app.js
  controllers/bookController.js
  controllers/hostController.js
  controllers/index.js
  controllers/likeController.js
  controllers/productController.js
  controllers/reviewController.js
  controllers/userController.js
  env_sample
  models/bookDao.js
  models/dataSource.js
  models/hostDao.js
  models/index.js
  models/likeDao.js
  models/productDao.js
  models/reviewDao.js
  models/userDao.js
  package-lock.json
  package.json
  routers/bookRouter.js
  routers/hostRouter.js
  routers/index.js
  routers/likeRouter.js
  routers/productRouter.js
  routers/reviewRouter.js
  routers/userRouter.js
  services/bookService.js
  services/hostService.js
  services/index.js
  services/likeService.js
  services/productService.js
  services/reviewService.js
  services/userService.js
  utils/auth.js
  utils/error.js
Labels: 완료

#2 O2bnb DB 테이블 생성
  .gitignore
  db/migrations/20221004072425_users.sql
  db/migrations/20221004072455_hosts.sql
  db/migrations/20221004072516_products.sql
  db/migrations/20221004072537_options.sql
  db/migrations/20221004072548_reviews.sql
  db/migrations/20221004072554_host_reviews.sql
  db/migrations/20221004072609_product_images.sql
  db/migrations/20221004072613_likes.sql
  db/migrations/20221004072624_bookings.sql
  db/migrations/20221004072634_booking_status.sql
  db/migrations/20221004103305_chatting.sql
  db/migrations/20221005061833_products_options.sql
  package.json
Labels: 멘토 리뷰 요청

#7 [정다영- O2bnb] Modify : Initial Setting
  .env.test
  .gitignore
  app.js
  db/migrations/20221004072516_products.sql
  package-lock.json
  package.json
  server.js
  src/controllers/bookController.js
  src/controllers/hostController.js
  src/controllers/index.js
  src/controllers/likeController.js
  src/controllers/productController.js
  src/controllers/reviewController.js
  src/controllers/userController.js
  src/models/bookDao.js
  src/models/dataSource.js
  src/models/hostDao.js
  src/models/index.js
  src/models/likeDao.js
  src/models/productDao.js
  src/models/reviewDao.js
  src/models/userDao.js
  src/routers/bookRouter.js
  src/routers/hostRouter.js
  src/routers/index.js
  src/routers/likeRouter.js
  src/routers/productRouter.js
  src/routers/reviewRouter.js
  src/routers/userRouter.js
  src/services/bookService.js
  src/services/hostService.js
  src/services/index.js
  src/services/likeService.js
  src/services/productService.js
  src/services/reviewService.js
  src/services/userService.js
  src/utils/auth.js
  src/utils/error.js
  tests/user.test.js
Labels: 멘토 리뷰 요청

#4 [정다영- O2bnb] ADD : GET 전체상품목록
  src/controllers/index.js
  src/controllers/productController.js
  src/models/index.js
  src/models/productDao.js
  src/routers/index.js
  src/routers/productRouter.js
  src/services/index.js
  src/services/productService.js
  src/utils/auth.js
  tests/user.test.js
Labels: 멘토 리뷰 요청

#6 [정다영- O2bnb] ADD : GET 단일제품정보
  db/migrations/20221004072455_hosts.sql
  server.js
  src/controllers/productController.js
  src/models/productDao.js
  src/routers/index.js
  src/routers/productRouter.js
  src/services/productService.js
Labels: 멘토 리뷰 요청

#8 [정다영- O2bnb] ADD : GET Price_Filter
  src/controllers/productController.js
  src/models/productDao.js
  src/routers/index.js
  src/routers/productRouter.js
  src/services/productService.js
Labels: 멘토 리뷰 요청

#9 [정다영- O2bnb] ADD : GET search_pricename
  server.js
  src/controllers/productController.js
  src/models/productDao.js
  src/routers/productRouter.js
  src/services/productService.js
Labels: 멘토 리뷰 요청

#5 [최진우 - O2bnb] 상품페이지 내 리뷰 불러오기 기능 구현
  .env.test
  .gitignore
  app.js
  db/migrations/20221004072623_booking_status.sql
  db/migrations/20221005061833_products_options.sql
  package-lock.json
  package.json
  server.js
  src/controllers/index.js
  src/controllers/reviewController.js
  src/models/dataSource.js
  src/models/index.js
  src/models/reviewDao.js
  src/routers/index.js
  src/routers/reviewRouter.js
  src/services/index.js
  src/services/reviewService.js
  tests/review.test.js
  tests/user.test.js
Labels: 멘토 리뷰 요청

#12 [최진우- O2bnb] ADD : POST, GET, PATCH book
  package-lock.json
  src/controllers/bookController.js
  src/controllers/index.js
  src/models/bookDao.js
  src/models/index.js
  src/routers/bookRouter.js
  src/routers/index.js
  src/services/bookService.js
  src/services/index.js
Labels: 수정 요청
